use clap::{Arg, ArgAction, ArgMatches, Command};

pub fn build() -> ArgMatches {
    Command::new(clap::crate_name!())
        .about(clap::crate_description!())
        .version(clap::crate_version!())
        // .author(clap::crate_authors!("\n"))
        .long_about("Gathers files from directories and subdirectories into a target directory.")
        .arg(
            Arg::new("read")
                .value_name("FILE(S)")
                .help("One or more file(s) to process. Wildcards and multiple_occurrences files (e.g. 2019*.pdf 2020*.pdf) are supported. Use ** glob to recurse (i.e. **/*.pdf). Note: Case sensitive.")
                .required(true)
                .num_args(1..)
                .action(ArgAction::Append)
        )
        .arg(
            Arg::new("target")
                .value_name("TARGET")
                .help("The target directory into which files are to be gathered.")
                .num_args(1)
                .required(true)
                .last(true)
                .action(ArgAction::Set)
        )
        .arg( // Move rather than copy files
            Arg::new("move")
                .short('m')
                .long("move")
                .help("Move files instead of copying them.")
                .num_args(0)
                .hide(false)
                .action(ArgAction::SetTrue)
        )
        .arg( // Stop on error
            Arg::new("stop")
                .short('s')
                .long("stop-on-error")
                .help("Stop on error. If this flag isn't set, the application will attempt to continue in case of error.")
                .num_args(0)
                .hide(false)
                .action(ArgAction::SetTrue)
        )
        .arg( // Dry-run
            Arg::new("dry-run")
                .short('r')
                .long("dry-run")
                .help("Iterate through the files and produce output without actually processing anything.")
                .num_args(0)
                .hide(false)
                .action(ArgAction::SetTrue)
        )
        .arg( // Hidden debug parameter
            Arg::new("debug")
                .short('d')
                .long("debug")
                .help("Output debug information as we go. Supply it twice for trace-level logs.")
                .hide(true)
                .env("GATHER_DEBUG")
                .num_args(0)
                .action(ArgAction::Count)
        )
        .arg( // Don't print any information
            Arg::new("quiet")
                .short('q')
                .long("quiet")
                .help("Don't produce any output except errors while working.")
                .num_args(0)
                .hide(false)
                .action(ArgAction::SetTrue)
        )
        .arg( // Print summary information
            Arg::new("summary")
                .short('p')
                .long("print-summary")
                .help("Print summary information about the number of files gathered.")
                .num_args(0)
                .hide(false)
                .action(ArgAction::SetTrue)
        )
        .arg( // Don't show detail information
            Arg::new("detail-off")
                .short('o')
                .long("detail-off")
                .help("Don't print detailed information about each file processed.")
                .num_args(0)
                .hide(false)
                .action(ArgAction::SetTrue)
        )
        .get_matches()
}
